### Create a room
POST http://localhost:8080/api/rooms/create
Content-Type: application/json

{
  "title": "Room 1",
  "date": "2024-10-26T14:48:00.000Z"
}

### Get room by code
GET http://localhost:8080/api/rooms/1WF2C9U3

### Create a group
POST http://localhost:8080/api/groups/create/1
Content-Type: application/json

{
  "destination": "gooreind",
  "transportType": "public_transport",
  "maxParticipants": null
}

### Add participant to group
POST http://localhost:8080/api/participants/add/1
Content-Type: application/json

{
  "name": "Joske Vermeulen",
  "destination": "Braschaat"
}

### Remove participant from group
DELETE http://localhost:8080/api/participants/remove/8/12